services:
    nextjs:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - "${PORT:-3000}:3000"
        volumes:
            - .:/app
        environment:
            NODE_ENV: development
        restart: always
